import io
import os
import tempfile
from fpdf import FPDF
import qrcode

UPLOAD_DIR = os.path.join(os.path.dirname(__file__), "..", "uploads")


def _qr_image(data: str) -> str:
    img = qrcode.make(data, box_size=4)
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    img.save(tmp.name)
    return tmp.name


def generate_case_pdf(victim, base_url: str = "http://127.0.0.1:5173") -> bytes:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)

    case_url = f"{base_url.rstrip('/')}/case.html?id={victim.id}"
    # QR1 always case verification URL; QR2 prefers victim's uploaded bank QR image (per user decision)
    qr_case_path = _qr_image(case_url)
    # If victim uploaded a bank QR, embed that image directly as donor QR; else generate donate URL QR
    bank_qr_path = None
    qr_donate_path = None
    qr_donate_is_temp = False
    if getattr(victim, "bank_qr", None):
        candidate = os.path.join(UPLOAD_DIR, victim.bank_qr)
        if os.path.exists(candidate):
            bank_qr_path = candidate
            qr_donate_path = bank_qr_path
        else:
            donate_url = f"{case_url}#donate"
            qr_donate_path = _qr_image(donate_url)
            qr_donate_is_temp = True
    else:
        donate_url = f"{case_url}#donate"
        qr_donate_path = _qr_image(donate_url)
        qr_donate_is_temp = True
    qr_case_is_temp = True

    # Helper
    def add_header(page_title: str):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(37, 99, 235)
        pdf.cell(0, 6, "TrustMed", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 4, "Verified Medical Crowdfunding  |  Case ID: " + (victim.case_id or f"#{victim.id}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(37, 99, 235)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    def add_footer():
        pdf.set_y(-18)
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 4, f"Generated by TrustMed  |  Page {pdf.page_no()}", align="C")

    def add_qr_side():
        y_start = pdf.get_y()
        # ensure we have paths
        try:
            pdf.image(qr_case_path, x=160, y=y_start, w=22, h=22)
        except Exception:
            pass
        pdf.set_xy(160, y_start + 23)
        pdf.set_font("Helvetica", "", 6)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(22, 3, "Scan to view case", align="C")
        try:
            pdf.image(qr_donate_path, x=185, y=y_start, w=22, h=22)
        except Exception:
            pass
        pdf.set_xy(185, y_start + 23)
        # label adapts if we are showing victim bank QR
        label = "Victim Bank QR" if bank_qr_path else "Scan to donate"
        pdf.cell(22, 3, label, align="C")

    pdf.set_text_color(0, 0, 0)

    # ── PAGE 1: Patient Overview ──
    pdf.add_page()
    add_header("VERIFICATION DOCUMENT")
    add_footer()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Patient Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Photo + details
    if victim.patient_photo:
        photo_path = os.path.join(UPLOAD_DIR, victim.patient_photo)
        if os.path.exists(photo_path):
            pdf.image(photo_path, x=12, y=pdf.get_y(), w=30, h=30)

    pdf.set_xy(46, pdf.get_y())
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 7, victim.name, new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(46)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Address: {victim.address}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(46)
    pdf.cell(0, 5, f"Phone: {victim.phone}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(46)
    pdf.cell(0, 5, f"Municipality: {victim.municipality_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(46)
    pdf.cell(0, 5, f"Hospital: {victim.hospital_name}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    pdf.set_x(46)
    pdf.set_text_color(22, 163, 74)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 5, "Hospital Verified  /  Municipality Approved", new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # Logos
    y_logo = pdf.get_y()
    if victim.hospital_logo:
        logo_path = os.path.join(UPLOAD_DIR, victim.hospital_logo)
        if os.path.exists(logo_path):
            pdf.image(logo_path, x=12, y=y_logo, w=30, h=10)
            pdf.set_xy(12, y_logo + 11)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(30, 3, victim.hospital_name, align="C")

    if victim.municipality_logo:
        logo2_path = os.path.join(UPLOAD_DIR, victim.municipality_logo)
        if os.path.exists(logo2_path):
            pdf.image(logo2_path, x=46, y=y_logo, w=30, h=10)
            pdf.set_xy(46, y_logo + 11)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(30, 3, victim.municipality_name, align="C")

    pdf.set_text_color(0, 0, 0)
    pdf.ln(14)

    # QR codes
    add_qr_side()

    # ── PAGE 2: Medical & Financial ──
    pdf.add_page()
    add_header("MEDICAL & FINANCIAL DETAILS")
    add_footer()
    add_qr_side()

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Medical & Financial Details", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Diagnosis / Disease: {victim.disease}", new_x="LMARGIN", new_y="NEXT")

    # Medical reports (small thumbnails)
    if victim.medical_reports:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 6, "Medical Reports:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(60, 60, 60)
        pdf.set_font("Helvetica", "", 8)
        for r in victim.medical_reports[:4]:
            pdf.cell(0, 4, f"  - {r.original_name}", new_x="LMARGIN", new_y="NEXT")
            rpath = os.path.join(UPLOAD_DIR, r.filename)
            if os.path.exists(rpath) and os.path.getsize(rpath) < 500000:
                try:
                    pdf.image(rpath, x=12, w=40, h=30)
                    pdf.ln(32)
                except Exception:
                    pass

    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Financial Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Estimated Treatment Cost: NPR {victim.estimated_cost:,.0f}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Total Collected: NPR {victim.total_collected or 0:,.0f}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 6, "Bank Account Details", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Bank: {victim.bank_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Account Holder: {victim.bank_account_holder}", new_x="LMARGIN", new_y="NEXT")
    # Mask raw account number — donors scan victim's Bank QR instead (privacy per your decision)
    pdf.cell(0, 5, "Account Number: **** (scan Bank QR to donate)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Branch: {victim.bank_branch}", new_x="LMARGIN", new_y="NEXT")
    # Embed expanded Bank QR image if available
    if bank_qr_path and os.path.exists(bank_qr_path):
        try:
            y_qr = pdf.get_y() + 2
            pdf.image(bank_qr_path, x=12, y=y_qr, w=36, h=36)
            pdf.set_xy(50, y_qr + 12)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 4, "Scan this QR with your banking app (Fonepay/ConnectIPS/eSewa/Khalti) — funds go directly to patient's bank.", new_x="LMARGIN", new_y="NEXT")
            pdf.set_y(y_qr + 38)
            pdf.set_text_color(60, 60, 60)
        except Exception:
            pass

    if victim.note_to_donors:
        pdf.ln(4)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, f'Note from patient: "{victim.note_to_donors}"')

    # ── PAGE 3: Collectors ──
    if victim.collectors and len(victim.collectors) > 0:
        pdf.add_page()
        add_header("VERIFIED COLLECTORS")
        add_footer()
        add_qr_side()

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Authorised Cash Collectors", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 4, "The following individuals are authorised to collect cash donations in person on behalf of the patient. This document serves as proof of authorization.")
        pdf.ln(4)

        for i, c in enumerate(victim.collectors, 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, f"Collector {i}: {c.name}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 4, f"  Address: {c.address}", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(0, 4, f"  Contact: {c.contact}", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(0, 4, f"  Relation to Patient: {c.relation_to_victim}", new_x="LMARGIN", new_y="NEXT")
            if c.citizenship_details:
                pdf.cell(0, 4, f"  Citizenship: {c.citizenship_details}", new_x="LMARGIN", new_y="NEXT")
            if c.photo:
                cphoto_path = os.path.join(UPLOAD_DIR, c.photo)
                if os.path.exists(cphoto_path):
                    try:
                        pdf.image(cphoto_path, x=12, w=20, h=20)
                    except Exception:
                        pass
            pdf.ln(22)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_y(-14)
    pdf.cell(0, 4, "This is a system-generated verification document from TrustMed.", align="C")

    # Cleanup temp QR images (do not delete victim uploaded bank_qr)
    try:
        if qr_case_is_temp and os.path.exists(qr_case_path):
            os.unlink(qr_case_path)
        if qr_donate_is_temp and qr_donate_path and os.path.exists(qr_donate_path):
            os.unlink(qr_donate_path)
    except Exception:
        pass

    return pdf.output()
